# Generated by Django 4.1.2 on 2022-10-06 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('credit', models.PositiveSmallIntegerField()),
                ('teacher', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('duration', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('nic', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('paternal_Surname', models.CharField(max_length=35)),
                ('mothers_surname', models.CharField(max_length=35)),
                ('names', models.CharField(max_length=35)),
                ('date_of_birth', models.DateField()),
                ('genre', models.CharField(choices=[('F', 'Feminine'), ('M', 'masculine')], default='F', max_length=1)),
                ('validity', models.BooleanField(default=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.race')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_registrations', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.student')),
            ],
        ),
    ]
